services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-net

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-net

  auth:
    build:
      context: ./auth
    container_name: auth
    depends_on:
      - mysql
    environment:
      - DB_DSN=root:password@tcp(mysql:3306)/authdb?charset=utf8mb4&parseTime=True&loc=Local
      - JWT_SECRET=supersecret
    ports:
      - "8081:8080"
    networks:
      - todo-net

  core:
    build:
      context: ./core
    container_name: core
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/tododb
      - JWT_SECRET=supersecret
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - todo-net

  web:
    build:
      context: ./web
    container_name: web
    depends_on:
      - core
      - auth
    ports:
      - "8080:80" # Nginx expone en 80
    networks:
      todo-net:
        ipv4_address: 172.20.0.10

volumes:
  mongo-data:
  mysql-data:

networks:
  todo-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
