apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn

---
# MySQL ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS authdb;

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-mysql-depl
  labels:
    app: todoapp-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp-mysql
  template:
    metadata:
      labels:
        app: todoapp-mysql
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: todoapp-mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h localhost -u root -pppassword
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d

      initContainers:
        - name: cleanup-data-dir
          image: busybox
          command: ["sh", "-c", "rm -rf /var/lib/mysql/*"]
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config

---
apiVersion: v1
kind: Service
metadata:
  name: todoapp-mysql-srv
spec:
  selector:
    app: todoapp-mysql
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
