apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: todoapp-prod-tls
  namespace: prod
spec:
  secretName: todoapp-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - dalthonmh.space
