apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

patches:
  - target:
      kind: Gateway
      name: todoapp-gateway
    patch: |-
      - op: add
        path: /spec/listeners/0/hostname
        value: dalthonmh.space

      - op: add
        path: /spec/listeners/-
        value:
          name: https
          protocol: HTTPS
          port: 443
          hostname: dalthonmh.space
          tls:
            mode: Terminate
            certificateRefs:
              - name: todoapp-prod-tls
                kind: Secret
          allowedRoutes:
            namespaces:
              from: Same

  - target:
      kind: HTTPRoute
      name: todoapp-route
    patch: |-
      - op: add
        path: /spec/hostnames
        value:
          - dalthonmh.space
