apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth
  # - core
  # - mongo
  - mysql
  - postgres
  - task
  - web

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: todoapp
    includeSelectors: true

commonAnnotations:
  contact: dalthonmh@gmail.com
