apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  use-forwarded-headers: "true"
  enable-ssl-passthrough: "true"
  proxy-connect-timeout: "30"
  proxy-read-timeout: "30"
  proxy-send-timeout: "30"
