apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-web-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp-web
  template:
    metadata:
      labels:
        app: todoapp-web
    spec:
      containers:
        - name: todoapp-web
          image: dalthonmh/todoapp-web
          env:
            - name: VITE_API_CORE_URL
              value: http://todoapp-core-srv:3000
            - name: VITE_API_AUTH_URL
              value: http://todoapp-auth-srv:3000

---
apiVersion: v1
kind: Service
metadata:
  name: todoapp-web-srv
spec:
  selector:
    app: todoapp-web
  ports:
    - name: todoapp-web
      protocol: TCP
      port: 3000
      targetPort: 3000
