apiVersion: v1
kind: PersistentVolume
metadata:
  name: sample-mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /mnt/data/sample-mysql
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-mysql-depl
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: sample-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-mysql
  template:
    metadata:
      labels:
        app: sample-mysql
    spec:
      containers:
        - name: sample-mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "my_database"
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: sample-mysql-storage
              mountPath: /var/lib/mysql
              subPath: mysql-data
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: sample-mysql-storage
          persistentVolumeClaim:
            claimName: sample-mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: sample-mysql-srv
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: sample-mysql
spec:
  selector:
    app: sample-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30033
  type: NodePort
