apiVersion: v1
kind: PersistentVolume
metadata:
  name: sample-posgresql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /mnt/data/sample-postgresql

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-posgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-posgresql-depl
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: sample-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-posgresql
  template:
    metadata:
      labels:
        app: sample-posgresql
    spec:
      containers:
        - name: sample-posgresql
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "my_database"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: sample-posgresql-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres-data
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: sample-posgresql-storage
          persistentVolumeClaim:
            claimName: sample-posgresql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: sample-posgresql-srv
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: sample-postgresql
spec:
  selector:
    app: sample-posgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30032
  type: NodePort
