apiVersion: apps/v1
kind: Deployment
metadata:
  name: task
spec:
  replicas: 1
  template:
    metadata:
    spec:
      initContainers:
        - name: init-postgres-wait
          image: busybox:1.28
          command:
            ["sh", "-c", "until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;"]
      containers:
        - name: task
          image: dalthonmh/todoapp-task:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILE
              value: prod
            - name: SERVER_PORT
              value: "8085"
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: taskdb
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: JWT_SECRET
              value: todoapp-my-secret-dalthonmh-jwtkey
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 25
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 40
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
