apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: components-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: todoapp
  source:
    repoURL: https://github.com/dalthonmh/todoapp.git
    targetRevision: HEAD
    path: infra/k8s/components/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
  # Note: Before this works correctly you must replace YOUR_VPS_IP
  # in infra/k8s/components/overlays/prod/kustomization.yaml
